### ISSUE TITLE
AbstractMethodError when using Grails 3.0.3 SNAPSHOT (20150626)

### ISSUE THREAD

**Issue by robertoschwald** [grails3-plugins/cache#2]
While working on a audit-logging plugin migration to Grails3, I suddenly received:

```
Caused by: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
Caused by: org.springframework.beans.PropertyBatchUpdateException: Failed properties: Property 'grailsApplication' threw exception; nested exception is java.lang.AbstractMethodError: grails.plugin.cache.CacheTagLib.setGrailsApplication(Lgrails/core/GrailsApplication;)V
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'grailsApplication' threw exception; nested exception is java.lang.AbstractMethodError: grails.plugin.cache.CacheTagLib.setGrailsApplication(Lgrails/core/GrailsApplication;)V
    at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:121) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at org.springframework.beans.Absat org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
ropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:121)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1510) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
    ... 53 common frames omitted
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1510)
    ... 53 more
```

I then created a plain Grails 3.0.2 test project to verify it is caused by the cache plugin:

Using Grails 3.0.2:

```
create-app grails3-cache-issue
cd grails3-cache-issue
```

Change in gradle.properties
    grailsVersion=3.0.3.BUILD-SNAPSHOT

Now try to start:

```
gradle run
```

Error occurs. Note that I haven't changed any code.

**Comment by robertoschwald** [comment]
As Graeme has written, seems to be a problem in WebAttributes trait in grails-core.

https://github.com/grails/grails-core/commit/a7d1ad52699d4a23f0e3db5f949dbae30895cdb3

Closing here.
